services:

  maven:
    image: maven:3.9.9-sapmachine-21
    container_name: ${MAVEN_CONTAINER_NAME}
    volumes:
      - .:/app
      - maven:/root/.m2/repository  # Volume pour le cache Maven
    working_dir: /app
    command: sleep infinity  # Garde le conteneur en marche sans rien faire
    env_file:
      - .env
    ports:
      - "${MAVEN_PORT_EXT}:${MAVEN_PORT_INT}"

  mysql:
    image: mysql:8.0
    container_name: ${MYSQL_CONTAINER_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_scripts/mysql:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT_EXT}:${MYSQL_PORT_INT}"
    env_file:
      - .env

  mongodb:
    image: mongo:6.0
    container_name: ${MONGODB_CONTAINER_NAME}
    volumes:
      - mongodb_data:/data/db
      - ./init_scripts/mangodb:/docker-entrypoint-initdb.d
    ports:
      - "${MONGODB_PORT_EXT}:${MONGODB_PORT_INT}"
    env_file:
      - .env

  angular:
    image: ghcr.io/${GHCR_PATH}/angular:latest
    build: ${BUILD_PATH_ANGULAR}
    container_name: ${ANGULAR_CONTAINER_NAME}
    volumes:
      - ./frontend/angular:/app
      - /app/node_modules
    ports:
      - "${ANGULAR_PORT_EXT}:${ANGULAR_PORT_INT}"
    depends_on:
      - gateway
    env_file:
      - .env

  note:
    image: ghcr.io/${GHCR_PATH}/note:latest
    build: ${BUILD_PATH_NOTE}
    container_name: ${NOTE_CONTAINER_NAME}
    volumes:
      - ./backend/note:/app
      - /app
    ports:
      - "${NOTE_PORT_EXT}:${NOTE_PORT_INT}"
    depends_on:
      - mongodb
    env_file:
      - .env

  patient:
    image: ghcr.io/${GHCR_PATH}/patient:latest
    build: ${BUILD_PATH_PATIENT}
    container_name: ${PATIENT_CONTAINER_NAME}
    volumes:
      - ./backend/patient:/app
      - /app
    ports:
      - "${PATIENT_PORT_EXT}:${PATIENT_PORT_INT}"
    depends_on:
      - mysql
    env_file:
      - .env

  report:
    image: ghcr.io/${GHCR_PATH}/report:latest
    build: ${BUILD_PATH_REPORT}
    container_name: ${REPORT_CONTAINER_NAME}
    volumes:
      - ./backend/report:/app
      - /app
    ports:
      - "${REPORT_PORT_EXT}:${REPORT_PORT_INT}"
    depends_on:
      - note
      - patient
    env_file:
      - .env

  gateway:
    image: ghcr.io/${GHCR_PATH}/gateway:latest
    build: ${BUILD_PATH_GATEWAY}
    container_name: ${GATEWAY_CONTAINER_NAME}
    volumes:
      - ./backend/gateway:/app
      - /app
    ports:
      - "${GATEWAY_PORT_EXT}:${GATEWAY_PORT_INT}"
    depends_on:
      - note
      - patient
      - report
    env_file:
      - .env

volumes:
  mysql_data:
  mongodb_data:
  maven: