server:
  port: 8080  # Port sur lequel le serveur écoute
logging:
  level:
    root: trace

spring:
  application:
    name: gateway  # Nom de l'application

  cloud:
    gateway:

      routes:
        #login check
        - id: login-check
          uri: no://op
          predicates:
            - Path=/api/auth
          filters:
            - SetStatus=200

        # Patient routes
        - id: patient-list
          uri: ${ROUTE_PATIENT}
          predicates:
            - Path=/api/clientele
          filters:
            - RewritePath=/api/clientele, /clientele
            # Incoming URL: http://<gateway-host>:8080/api/clientele
            # Outgoing URL: ${ROUTE_PATIENT}/clientele

        - id: patient-details
          predicates:
            - Path=/api/clientele/patient/{patientId:\d+}
          uri: ${ROUTE_PATIENT}
          filters:
            - RewritePath=/api/clientele/patient/(?<patientId>.*), /patient/${patientId}
          # Incoming URL: http://<gateway-host>:8080/api/clientele/patient/{patientId}
          # Outgoing URL: ${ROUTE_PATIENT}/patient/{patientId}

        - id: patient-update
          predicates:
            - Path=/api/clientele/patient
          uri: ${ROUTE_PATIENT}
          filters:
            - RewritePath=/api/clientele/patient, /patient
          # Incoming URL: http://<gateway-host>:8080/api/clientele/patient
          # Outgoing URL: ${ROUTE_PATIENT}/patient

        # FollowNote routes
        - id: notes-list
          predicates:
            - Path=/api/clientele/patient/notes/{patientId:\d+}
          uri: ${ROUTE_NOTE}
          filters:
            - RewritePath=/api/clientele/patient/notes/(?<patientId>.*), /notes/${patientId}
          # Incoming URL: http://<gateway-host>:8080/api/clientele/patient/notes/{patientId}
          # Outgoing URL: ${ROUTE_NOTE}/notes/{patientId}

        - id: note-add
          predicates:
            - Path=/api/clientele/patient/notes/note
          uri: ${ROUTE_NOTE}
          filters:
            - RewritePath=/api/clientele/patient/notes/note, /note
          # Incoming URL: http://<gateway-host>:8080/api/clientele/patient/notes/note
          # Outgoing URL: ${ROUTE_NOTE}/note

        # Report routes
        - id: report-risk
          predicates:
            - Path=/api/clientele/patient/notes/report/{patientId:\d+}
          uri: ${ROUTE_REPORT}
          filters:
            - RewritePath=/api/clientele/patient/notes/report/(?<patientId>.*), /report/${patientId}
          # Incoming URL: http://<gateway-host>:8080/api/clientele/patient/notes/report/{patientId}
          # Outgoing URL: ${ROUTE_REPORT}/report/{patientId}

        # Wrong routes
        - id: fallback-route
          predicates:
            - Path=/**
          uri: forward:/fallback
          # redirect on controller's gateway fallback to return responseStatus BAD_GATEWAY
