/**
 * DTO class for representing the response of a report.
 */
package com.thery.report.dto;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Constructor to create a ReportResponse object with specified risk estimation.
 */
@AllArgsConstructor
@Getter
public class ReportResponse {

    String riskEstimation;

    /**
     * Default constructor for ReportResponse.
     * This constructor is generated by Lombok.
     */
    public ReportResponse() {
        //lombok constructor
    }
}